import { Activity } from "./activity";

export const mockActivities: Activity[] = [
  {
    id: '1',
    title: 'Neural Networks Deep Dive',
    type: 'online-class',
    subject: 'Machine Learning',
    status: 'not-started',
    description: 'Comprehensive overview of neural network architectures including CNNs and RNNs',
    startTime: '2025-11-27T14:00:00',
    duration: '90 min',
    instructor: 'Dr. Sarah Chen',
    totalStudents: 156,
  },
  {
    id: '2',
    title: 'AWS Cloud Architecture Assignment',
    type: 'assignment',
    subject: 'Cloud Computing',
    status: 'in-progress',
    description: 'Design and document a scalable cloud infrastructure for a high-traffic web application',
    dueDate: '2025-11-28T23:59:00',
    duration: '4-6 hours',
    points: 100,
    progress: 45,
  },
  {
    id: '3',
    title: 'Machine Learning Algorithms Quiz',
    type: 'quiz',
    subject: 'Machine Learning',
    status: 'overdue',
    description: 'Test your knowledge on supervised and unsupervised learning algorithms',
    dueDate: '2025-11-25T23:59:00',
    duration: '45 min',
    points: 50,
  },
  {
    id: '4',
    title: 'Ethics in AI Discussion',
    type: 'discussion',
    subject: 'AI',
    status: 'in-progress',
    description: 'Share your thoughts on the ethical implications of AI in healthcare',
    dueDate: '2025-11-29T23:59:00',
    submissions: 23,
    totalStudents: 156,
    progress: 60,
  },
  {
    id: '5',
    title: 'Introduction to Transformers',
    type: 'online-class',
    subject: 'AI',
    status: 'completed',
    description: 'Learn about transformer architecture and attention mechanisms',
    startTime: '2025-11-20T10:00:00',
    duration: '120 min',
    instructor: 'Prof. James Liu',
    totalStudents: 142,
  },
  {
    id: '6',
    title: 'Kubernetes Deployment Project',
    type: 'assignment',
    subject: 'Cloud Computing',
    status: 'not-started',
    description: 'Deploy a containerized application using Kubernetes with auto-scaling',
    dueDate: '2025-12-05T23:59:00',
    duration: '6-8 hours',
    points: 150,
  },
  {
    id: '7',
    title: 'Deep Learning Fundamentals',
    type: 'online-class',
    subject: 'Machine Learning',
    status: 'in-progress',
    description: 'Foundational concepts of deep learning and backpropagation',
    startTime: '2025-11-26T16:00:00',
    duration: '90 min',
    instructor: 'Dr. Emily Rodriguez',
    totalStudents: 178,
    progress: 30,
  },
  {
    id: '8',
    title: 'Natural Language Processing Quiz',
    type: 'quiz',
    subject: 'AI',
    status: 'not-started',
    description: 'Assessment on NLP techniques including tokenization, embeddings, and sentiment analysis',
    dueDate: '2025-11-30T23:59:00',
    duration: '60 min',
    points: 75,
  },
  {
    id: '9',
    title: 'Microservices Architecture Discussion',
    type: 'discussion',
    subject: 'Cloud Computing',
    status: 'completed',
    description: 'Compare microservices vs monolithic architecture approaches',
    dueDate: '2025-11-22T23:59:00',
    submissions: 89,
    totalStudents: 112,
  },
  {
    id: '10',
    title: 'Time Series Forecasting Assignment',
    type: 'assignment',
    subject: 'Machine Learning',
    status: 'overdue',
    description: 'Build a model to forecast stock prices using LSTM networks',
    dueDate: '2025-11-24T23:59:00',
    duration: '5-7 hours',
    points: 120,
    progress: 20,
  },
  {
    id: '11',
    title: 'Computer Vision Techniques',
    type: 'online-class',
    subject: 'AI',
    status: 'not-started',
    description: 'Explore image classification, object detection, and semantic segmentation',
    startTime: '2025-12-01T14:00:00',
    duration: '90 min',
    instructor: 'Dr. Michael Park',
    totalStudents: 134,
  },
  {
    id: '12',
    title: 'Cloud Security Best Practices Discussion',
    type: 'discussion',
    subject: 'Cloud Computing',
    status: 'not-started',
    description: 'Discuss strategies for securing cloud infrastructure and data',
    dueDate: '2025-12-03T23:59:00',
    submissions: 12,
    totalStudents: 112,
  },
  {
    id: '13',
    title: 'Reinforcement Learning Quiz',
    type: 'quiz',
    subject: 'Machine Learning',
    status: 'completed',
    description: 'Test your understanding of Q-learning, policy gradients, and reward functions',
    dueDate: '2025-11-18T23:59:00',
    duration: '45 min',
    points: 60,
  },
  {
    id: '14',
    title: 'Building a Chatbot with GPT',
    type: 'assignment',
    subject: 'AI',
    status: 'in-progress',
    description: 'Create a conversational AI chatbot using OpenAI GPT API',
    dueDate: '2025-12-01T23:59:00',
    duration: '8-10 hours',
    points: 200,
    progress: 55,
  },
  {
    id: '15',
    title: 'Serverless Computing Workshop',
    type: 'online-class',
    subject: 'Cloud Computing',
    status: 'not-started',
    description: 'Hands-on workshop on AWS Lambda, Azure Functions, and serverless architectures',
    startTime: '2025-11-29T10:00:00',
    duration: '120 min',
    instructor: 'Prof. Anna Thompson',
    totalStudents: 98,
  },
];